# Optional HTTP virtualhost include. Use this if cPanel Force HTTPS Redirect
# is not handling the redirect for this subdomain.
# Install inside:
# /etc/apache2/conf.d/userdata/std/2_4/<cpanel_user>/futbol.astrogatolabs.com.mx/redirect_https.conf

RewriteEngine On
RewriteRule ^ https://futbol.astrogatolabs.com.mx%{REQUEST_URI} [R=301,L,NE]
