# Install inside:
# /etc/apache2/conf.d/userdata/ssl/2_4/<cpanel_user>/futbol.astrogatolabs.com.mx/streamlit_proxy.conf

ProxyPreserveHost On
ProxyRequests Off

RequestHeader set X-Forwarded-Proto "https"
RequestHeader set X-Forwarded-Host "futbol.astrogatolabs.com.mx"
RequestHeader set X-Forwarded-Port "443"

ProxyPass "/_stcore/stream" "ws://127.0.0.1:8501/_stcore/stream"
ProxyPassReverse "/_stcore/stream" "ws://127.0.0.1:8501/_stcore/stream"

ProxyPass "/" "http://127.0.0.1:8501/"
ProxyPassReverse "/" "http://127.0.0.1:8501/"
